### ISSUE TITLE
React FTW!

### ISSUE THREAD

**Issue by ecwyne** [MikkelSandbag/inventory-app#1]
Hey @MikkelSandbag!

This repo popped up on my homepage and I see you're using React. I use react for all of my projects now and I'm still loving it! (I also use `react-bootstrap` pretty extensively)

A couple of other libraries I'd be remiss if I didn't mention
1. [recompose](https://github.com/acdlite/recompose) - I use it all over the place (especially `withState`/`withHandlers`) so that I almost never have to use class components ([Top 5 Recompose HOCs](https://medium.com/@abhiaiyer/top-5-recompose-hocs-1a4c9cc4566))
2. [react-router](https://github.com/ReactTraining/react-router) - the name says it all
3. [ramda](http://ramdajs.com/docs/) - not react-specific but I use it in lieu of lodash/underscore
4. [apollo-*](https://www.apollographql.com/client/) - if you're looking into using GraphQL with React at all, you've got to look into apollo

Let me know if you ever want to chat about react or if you run into any issues!

**Comment by MikkelSandbag** [comment]
Cool, thanks for the suggestions Eric :)
